/**
 * Error codes for structured error responses
 *
 * Categorized by domain and operation type
 */

export enum ErrorCode {
  // General errors
  UNKNOWN_ERROR = 'UNKNOWN_ERROR',
  INVALID_PARAMS = 'INVALID_PARAMS',
  NOT_IMPLEMENTED = 'NOT_IMPLEMENTED',

  // Browser/CDP errors
  CDP_CONNECTION_FAILED = 'CDP_CONNECTION_FAILED',
  CDP_METHOD_FAILED = 'CDP_METHOD_FAILED',
  BROWSER_NOT_CONNECTED = 'BROWSER_NOT_CONNECTED',
  PAGE_NOT_FOUND = 'PAGE_NOT_FOUND',

  // Element/Target errors
  ELEMENT_NOT_FOUND = 'ELEMENT_NOT_FOUND',
  ELEMENT_NOT_VISIBLE = 'ELEMENT_NOT_VISIBLE',
  ELEMENT_NOT_INTERACTABLE = 'ELEMENT_NOT_INTERACTABLE',
  SELECTOR_INVALID = 'SELECTOR_INVALID',
  TARGET_RESOLUTION_FAILED = 'TARGET_RESOLUTION_FAILED',

  // Navigation errors
  NAVIGATION_FAILED = 'NAVIGATION_FAILED',
  NAVIGATION_TIMEOUT = 'NAVIGATION_TIMEOUT',
  URL_INVALID = 'URL_INVALID',

  // Interaction errors
  CLICK_FAILED = 'CLICK_FAILED',
  TYPE_FAILED = 'TYPE_FAILED',
  UPLOAD_FAILED = 'UPLOAD_FAILED',
  SCROLL_FAILED = 'SCROLL_FAILED',
  KEYBOARD_FAILED = 'KEYBOARD_FAILED',

  // Form errors
  FORM_NOT_FOUND = 'FORM_NOT_FOUND',
  FORM_FIELD_NOT_FOUND = 'FORM_FIELD_NOT_FOUND',
  FORM_FILL_FAILED = 'FORM_FILL_FAILED',

  // Session errors
  SESSION_NOT_FOUND = 'SESSION_NOT_FOUND',
  COOKIE_SET_FAILED = 'COOKIE_SET_FAILED',
  STATE_RESTORE_FAILED = 'STATE_RESTORE_FAILED',

  // Perception errors
  DOM_TREE_FAILED = 'DOM_TREE_FAILED',
  AX_TREE_FAILED = 'AX_TREE_FAILED',
  LAYOUT_FAILED = 'LAYOUT_FAILED',
  VISION_FAILED = 'VISION_FAILED',
  CONTENT_EXTRACTION_FAILED = 'CONTENT_EXTRACTION_FAILED',
  NETWORK_OBSERVATION_FAILED = 'NETWORK_OBSERVATION_FAILED',

  // Timeout errors
  TIMEOUT = 'TIMEOUT',
  WAIT_CONDITION_TIMEOUT = 'WAIT_CONDITION_TIMEOUT',
}

/**
 * Error severity levels for logging and monitoring
 */
export enum ErrorSeverity {
  DEBUG = 'debug',
  INFO = 'info',
  WARNING = 'warning',
  ERROR = 'error',
  CRITICAL = 'critical',
}
